apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: teamflow
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://<user>:<pass>@cluster0.mongodb.net/teamprojectdb"
  JWT_SECRET: "replace_with_strong_secret"
